NVIDIA/egl-wayland

- wayland-eglstream/wayland-eglstream.xml
This fixes the DTD errors that were made noticeable by generating the
wayland protocol marshalling code automatically from the Makefile. The
DTD specifies the element order as (description? , entry*), not
(entry* , description?).
No functional changes are made to the protocol.
> Fix DTD errors in wayland-eglstream.xml

- Makefile.am
- configure.ac
- wayland-eglstream-protocols.pc.in
- wayland-eglstream.pc.in
Since I finally managed to get Xwayland working with eglstreams, I figured it's about time to start cleaning things up and preparing to get these patches submitted at some point.
That being said, this patch series allows Xwayland and other projects to actually build against egl-wayland using pkg-config, so that we don't have to reinclude the same wayland protocol files for every project.
Wayland protocols are installed (by default) in `/usr/local/share/egl-wayland/wayland-eglstream*.xml`, similarly to the path scheme of the official wayland-protocols package. Everything else is installed in the usual directories.
> More build system improvements

- meson.build
The Meson build system
Version: 0.46.1
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 364, in run
app.generate()
File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 135, in generate
self._generate(env)
File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 186, in _generate
intr.run()
File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 3261, in run
super().run()
File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 215, in run
self.evaluate_codeblock(self.ast, start=1)
File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 239, in evaluate_codeblock
raise e
File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 231, …
> meson: fix RuntimeError

- wayland-eglstream/meson.build
The option "code" was deprecated in favour of "public-code" with a
warning message produced to guide people.
Fixes: https://github.com/NVIDIA/egl-wayland/issues/14
> meson: replace 'private-code' on 'public-code'

- src/wayland-eglstream-server.c
The wl_eglstream_display::caps event currently ends up containing random garbage data, because the wl_eglstream_display_bind never initializes the supported_caps field value before it starts setting bits on it.
This changes it to use calloc to just zero the whole wl_eglstream_display struct before it starts filling anything in.
> Fix sending garbage data in the wl_eglstream_display::caps event

- m4/ax_check_compile_flag.m4
Some autoconf versions might not define AX_CHECK_COMPILE_FLAG, causing
configure to fail with:
./configure: line 18106: syntax error near unexpected token `-fvisibility=hidden,'
./configure: line 18106: `AX_CHECK_COMPILE_FLAG(-fvisibility=hidden,'
Fix that by providing the definition of AX_CHECK_COMPILE_FLAG.
Signed-off-by: Miguel A Vico Moya <mvicomoya@nvidia.com>
> Add definition of AX_CHECK_COMPILE_FLAG for older autoconf versions

- meson.build
The pkgconfig file wayland-eglstream.pc has instructions for linking to
an architecture specific library, so it should be installed to libdir
instead of datadir.
This is important on systems with multilib or multiarch, to make sure
that you link to the correct architecture version of the installed
libraries when multiple architectures are present.
> Install arch-specific pkgconfig file to libdir

- include/wayland-eglsurface.h
- src/wayland-eglsurface.c
- src/wayland-eglswap.c
As explained in #52 and https://github.com/libsdl-org/SDL/pull/4821, several games are broken under nVidia/Wayland due to calling wl_egl_window_resize() from a different thread.
This change works around this by deferring the resize until eglSwapBuffers(), which fixes the aforementioned games.
I'm not sure if this is the right solution to this problem — and the implementation could use a lot of cleanup, even so, but it seems to be a marked improvement for me.
> Defer resizes until next SwapBuffers (work around #52)

- src/wayland-egldisplay.c
These object are created but never destroyed. When the library is unload this leaves dangling pointers in libwayland-client leading to things like:
https://bugzilla.mozilla.org/show_bug.cgi?id=1759315
> Destroy all created wayland object in terminateDisplay

- src/wayland-egldisplay.c
libwayland 1.22 added a [warning](https://gitlab.freedesktop.org/wayland/wayland/-/blob/1.22.0/src/wayland-client.c?ref_type=tags#L308) that could currently be triggered by running `eglgears_wayland` under NVIDIA wayland:
```
warning: queue 0x5560c4ce1b30 destroyed while proxies still attached:
wl_registry@3 still attached
```
Firefox currently [crashes](https://bugzilla.mozilla.org/show_bug.cgi?id=1826583) upon such warnings. Mesa has fixed a similar bug in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21646
> Fix wrong destruction order for event queue

- Makefile.am
- configure.ac
- src/meson.build
- src/wayland-egldisplay.c
Compositors start dropping support for wl_drm because it is replaced by linux-dmabuf. See https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/2f2a55ebd3c5a950f1bf8c280edf0838721363da. Try reading compositors main device from linux-dmabuf v4 if supported and otherwise fallback to wl_drm.
> egl-wayland: Read compositor device from zwp_linux_dmabuf_v1

- Makefile.am
- include/wayland-egldisplay.h
- include/wayland-eglhandle.h
- include/wayland-eglsurface-internal.h
- src/meson.build
- src/wayland-egldisplay.c
- src/wayland-eglhandle.c
- src/wayland-eglsurface.c
- src/wayland-eglswap.c
This implements the explicit sync linux-drm-syncobj-v1 protocol for EGL.
This pull request exists to publicize our EGL implementation of explicit sync that we have been using to test the Mutter and Xwayland implementations. Erik and I have done a good amount of testing with this so it's in a fairly polished state and isn't just a first prototype.
Currently the code as proposed here will not build or run on existing drivers. To build it would need an updated wayland-protocols that contains linux-drm-syncobj, and to run it would require a newer (next upcoming release) NVIDIA driver that has the necessary prerequisites. Whenever this lands the minimum required NVIDIA driver version will also be bumped.
This change finally does away with the background threads which have given us issues in …
> Implement Explicit Sync

- src/wayland-external-exports.c
This fixes the ABI version check in loadEGLExternalPlatform. It currently uses `EGL_EXTERNAL_PLATFORM_VERSION_CHECK`, which is correct for what `EGL_EXTERNAL_PLATFORM_HAS` does, but it's backwards from what we need to check the driver version.
> Fix the ABI version check.

- src/wayland-eglsurface.c
This seems to be the appropriate type representation for timeout, moreover it also fixes an error with newer compilers where it complains about type mismatch between EGLint and EGL_FOREVER because EGL_FOREVER is defined as 0xFFFFFFFFFFFFFFFFull which is unsinged long long.
Fixes
| ../git/src/wayland-eglsurface.c:1591:62: error: implicit conversion from 'unsigned long long' to 'EGLint' (aka 'int') changes value from 18446744073709551615 to -1 [-Werror,]
|  1591 |     EGLint                timeout = surface->wlSyncobjSurf ? EGL_FOREVER : 0;
|       |                           ~~~~~~~                            ^~~~~~~~~~~
| /mnt/b/yoe/master/build/tmp/work/armv8a-yoe-linux/egl-wayland/1.1.13+git/recipe-sysroot/usr/include/EGL/egl.h:293:43: note: expanded from macro 'EGL_FOREVER'
|   293 | …
> wayland-eglsurface: Change type of timout from EGLint -> EGLTime

- src/wayland-eglsurface.c
It was assumed that the presence of the EGL_PRESENT_OPAQUE_EXT enum in the surface attribute list meant that the alpha channel should be ignored as if it was always followed by a value of EGL_TRUE, however, according to the spec, valid usage allows for a value of EGL_FALSE as well, which should result in the alpha channel being used for blending.
Validate and use the value instead of assuming that the presence of the extension enum value implies that it is enabled.
> egl-wayland: Validate and use the passed value of EGL_EXT_present_opaque

- configure.ac
- include/wayland-external-exports.h
- meson.build
- src/wayland-egldisplay.c
- src/wayland-eglsurface.c
This brings a few explicit sync fixes and bumps the version number to `1.1.14`. We can then make a new release tag containing explicit sync.
cc: @cubanismo @kbrenneman
> Update to 1.1.14

- src/wayland-eglsurface.c
Reported by a static analysis tool:
```
1. src/wayland-eglsurface.c:248:17: thread1_checks_field: Thread1 uses the value read from field "framesProcessed" in the condition "surface->ctx.framesFinished != surface->ctx.framesProcessed".It sees that the condition is true. Control is switched to Thread2.
2. src/wayland-eglsurface.c:248:17: thread2_checks_field: Thread2 uses the value read from field "framesProcessed" in the condition "surface->ctx.framesFinished != surface->ctx.framesProcessed". It sees that the condition is true.
3. src/wayland-eglsurface.c:255:17: thread2_acquires_lock: Thread2 acquires lock "WlEglSurfaceRec.mutexFrameSync".
4. src/wayland-eglsurface.c:260:17: thread2_modifies_field: Thread2 sets "framesProcessed" to a new value. Note that this write can be reordered at …
```
> wayland-egl: Fix race condition in damage_thread

- include/wayland-eglsurface-internal.h
- src/wayland-eglsurface.c
We do not seem to shrink the dynamically allocated streamImages array that we use for storing the resources associated with the swapchain images. When an entry in this array is destroyed in the destroy_stream_image() function, its fields are simply reverted to default/invalid values. Later on, the entries in this array are tried to be recycled in the add_surface_image() function. However, this approach is error-prone since we keep valid and invalid entries together, which requires us to check the validity of the entries every time we access them. Also, when explicit sync is in use, this array just keeps growing over time, especially during the application window resizes, due to a bug in the entry destruction logic.
So, to solve these problems, this change converts the dynamically …
> egl-wayland: Fix an unbounded array growth issue

- src/wayland-eglsurface.c
BSD variants do not define ETIME. So, the assert() call which verifies that errno is set to ETIME introduced in an earlier change could cause problems with debug builds on BSDs. This change adds preprocessor directives to limit that assertion to Linux.
> egl-wayland: Verify that errno is ETIME only on Linux

- src/wayland-egldisplay.c
There are still many application bugs caused by incorrect threading guarantees when running with explicit sync. This change implements a method for users to disable explicit sync manually for a particular application, in case there are issues with explicit sync.
Setting __NV_DISABLE_EXPLICIT_SYNC=1 will prevent the usage of explicit sync and fall back to the old method.
Tested disabling explicit sync on KDE, built on FreeBSD as well.
> egl-wayland: Add __NV_DISABLE_EXPLICIT_SYNC environment variable

- src/wayland-egldisplay.c
- src/wayland-eglsurface.c
This fixes two issues:
* eglCreateSync takes ownership of the fd passed to it, so we shoul not close the fd after passing it in.
* eglStreamAcquireImage's failure case only bails out of the function if acquireSync is valid, which is not the case when explicit sync is not in use.
> egl-wayland: Fix eglCreateSync and streamAcquireImage handling

- Makefile.am
- configure.ac
- meson.build
- src/meson.build
This just adds a dependency on the EGL headers (but not the libraries) to the build scripts.
I doubt that in practice we'll have to worry about egl.h and friends being in some strange location, so this mainly just provides a clearer error message if they're missing.
> Add an explicit dependency on the EGL headers.

- configure.ac
- include/wayland-external-exports.h
- meson.build
We are changing the release process and bumping versions immediately after a release tag is made, that way versions installed from the latest git master will always have the "next" version.
> Bump version to 1.1.17

- include/wayland-eglsurface-internal.h
- src/wayland-eglsurface.c
- src/wayland-eglswap.c
This is a rebase of a single commit from #50 that provides damage rectangles for wl_surfaces so the compositor knows which parts of the surfaces are damaged instead of just always damaging the surface as a whole.
I set @chergert as commit author since the changes of this commit are identical to his.
I didn't include the part that supports the damage_thread yet from #50 because [the damage thread is apparently gone when using explicit sync](https://github.com/NVIDIA/egl-wayland/pull/50#issuecomment-2305484091), this seems to also be sufficient to get applications such as Nautilus to only redraw the parts they need to, and this keeps the diff smaller. (In https://github.com/NVIDIA/egl-wayland/pull/50#issuecomment-2302748546 I also rebased the other commit, but we can add that separately if …
> Provide damage rectangles to wl_surface to avoid damaging entire surface when only parts of it need to be

- src/wayland-egldisplay.c
- src/wayland-eglsurface.c
This is a couple of minor build fixes.
In wayland-eglsurface.c, it tries to include `<libdrm/drm_fourcc.h>`, but there's no actual requirement that `drm_fourcc.h` should be in a `libdrm` subdirectory (even if it usually is). We already use pkg-config to add the appropriate include path for libdrm, so there's no need to hard-code a subdirectory for it.
The other just moves a declaration to the top of a function, since older compilers don't let you mix declarations and code.
> A couple of build fixes

- src/wayland-eglsurface.c
This is a follow-up to #138, to use INT32_MAX instead of UINT32_MAX for the wl_surface::damage request, since the protocol defines that as taking a signed int.
> Use INT32_MAX for wl_surface_damage

- src/wayland-egldisplay.c
This fixes a problem in commit 6355c16 where we do not properly wait for a roundtrip to get the wl_drm name, which can lead to failing to initialize and falling back to another ICD. This fix also properly prioritizes the device provided by dmabuf feedback over the wl_drm name, only using wl_drm if dmabuf did not provide anything.
> egl-wayland: fix device name case where only wl_drm exists

- src/10_nvidia_wayland.json
- src/meson.build
For `egl-x11` we are shipping the ICD json loaders as part of the source. For `egl-wayland` we are not.
Also make sure the json file has the same name as the one that is shipped with the Nvidia driver.
> Add ICD json file

- .github/workflows/arch-build.yml
- .github/workflows/autoconf-build.yml
- .github/workflows/meson-build.yml
- .github/workflows/meson-llvm-build.yml
This enables CI for github actions builds, aimed for helping verify new pull requests. This adds tests for the meson and autotools builds on ubuntu 24.04. Other distros are apparently not supported by default so we aren't able to expand testing this way.
We will need to add things like other distro support, FreeBSD CI, etc in the future but this is a good start for now.
> egl-wayland: enable CI with github actions

- src/wayland-egldisplay.c
This patch extends the hack described [here](https://github.com/NVIDIA/egl-wayland/blob/c10c5300483a8ec975e64e5d76c0fb00ac94e026/src/wayland-egldisplay.c#L692) to wlEglDestroyFeedback which might destroy a zwp_linux_dmabuf_feedback_v1 object.
I encountered a segmentation fault at termination of the game celeste because of this
> egl-wayland: Fix use after free at library teardown

- src/wayland-eglsurface.c
By the EGL spec, you're not allowed to create more than one EGLSurface from the same native window/pixmap. Currently, egl-wayland only partially checks for that, but you can still cause problems in a slightly more roundabout way.
While egl-wayland does check if the app tries to create a second EGLSurface from the same `wl_egl_window`, it's still possible to create more than one EGLSurface from the same `wl_surface`. Since `wl_egl_window_create` itself doesn't check for duplicates, you can create more than one `wl_egl_window` from the same `wl_surface`, and then create an EGLSurface for each.
With this change, egl-wayland will scan the list of EGLSurfaces to check if any of them use the same underlying `wl_surface`, and if it finds one, it'll fail eglCreateWindowSurface with EGL_BAD_ALLOC. …
> Check duplicate native surfaces

- configure.ac
- include/wayland-external-exports.h
- meson.build
Since 1.1.17 was just posted to correspond with the 565 release this bumps the latest development version to 1.1.18.
> egl-wayland: bump version to 1.1.18

- src/wayland-eglsurface.c
Previously, we were reading 0 bytes and were passing uninitialized value to `switch`. Likely, not much changed in practice (all codepaths were just terminating the thread, regardless of the success of the `read`), but now we don't trigger undefined behavior.
> Fix read return value check in buffer_release_thread

- include/wayland-egldisplay.h
- src/wayland-egldisplay.c
- src/wayland-external-exports.c
This removes `EGL_EXT_present_opaque` from the `EGL_EXT_PLATFORM_DISPLAY_EXTENSIONS` query, and instead adds a hook for `eglQueryString` to report it.
Any extensions in `EGL_EXT_PLATFORM_DISPLAY_EXTENSIONS` get added to *every* EGLDisplay, not just the ones that belong to egl-wayland. That's what we want for things like `EGL_WL_bind_wayland_display`, which is implemented in egl-wayland, but used in a compositor (generally with a device or GBM-based display).
For `EGL_EXT_present_opaque`, we need to report that through an `eglQueryString` hook instead. Unfortunately, current drivers won't call an eglQueryString hook, so without an updated driver, this will remove `EGL_EXT_present_opaque` from Wayland EGLDisplays as well. But, that's still better than advertising it on non-Wayland …
> Fix reporting EGL_EXT_present_opaque

- src/wayland-egldisplay.c
This change adds support in the Wayland EGL Platform library for the tegradisp-drm DRM driver meant for Automotive (DRIVE OS) Tegra platforms.
> egl-wayland: Add support for tegradisp-drm

- include/wayland-eglhandle.h
- src/wayland-egldisplay.c
- src/wayland-eglhandle.c
If the compositor does not support wl_drm and we fail to get the drmGetDeviceFromDevId symbol then the driver load will fail. This happens with steam due to it hijacking dlopen/dlsym. This change has us directly dlopen libdrm and get a symbol from it instead of relying on RTLD_DEFAULT.
> egl-wayland: Fix libdrm loading when wl_drm is not available
